#ifndef KOYOTECOIN_CHAINPARAMSSEEDS_H
#define KOYOTECOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,
    0x04,
    0xbf,
    0xfd,
    0x62,
    0xcd,
    0x1f,
    0xaf,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,
    0x04,
    0xbf,
    0xfd,
    0x62,
    0xcd,
    0x1f,
    0xaf,
};
#endif // KOYOTECOIN_CHAINPARAMSSEEDS_H
